In [1]:
import pandas as pd
import json
from random import shuffle

# 数据说明

In [2]:
news = pd.read_csv('./data/MIND/news.tsv', sep='\t', header=None)

In [3]:
news.columns = ["ID", "类别", "子类别", "标题", "摘要", "链接", "标题实体", "摘要实体"]

In [4]:
news.head(3)

,ID,类别,子类别,标题,摘要,链接,标题实体,摘要实体
0,N55528,lifestyle,lifestyleroyals,"The Brands Queen Elizabeth, Prince Charles, an...","Shop the notebooks, jackets, and more that the...",https://assets.msn.com/labs/mind/AAGH0ET.html,"[{""Label"": ""Prince Philip, Duke of Edinburgh"",...",[]
1,N19639,health,weightloss,50 Worst Habits For Belly Fat,These seemingly harmless habits are holding yo...,https://assets.msn.com/labs/mind/AAB19MK.html,"[{""Label"": ""Adipose tissue"", ""Type"": ""C"", ""Wik...","[{""Label"": ""Adipose tissue"", ""Type"": ""C"", ""Wik..."
2,N61837,news,newsworld,The Cost of Trump's Aid Freeze in the Trenches...,Lt. Ivan Molchanets peeked over a parapet of s...,https://assets.msn.com/labs/mind/AAJgNsz.html,[],"[{""Label"": ""Ukraine"", ""Type"": ""G"", ""WikidataId..."

In [5]:
news.shape

(51282, 8)

In [6]:
behaviors = pd.read_csv('./data/MIND/behaviors.tsv', sep='\t', header=None)
behaviors = behaviors.fillna('')

In [7]:
behaviors.columns = ["曝光ID", "用户ID", "曝光时间", "曝光前的新闻点击历史", "曝光明细 (1表示点击；0表示非点击)"]

In [8]:
behaviors.head(33)

,曝光ID,用户ID,曝光时间,曝光前的新闻点击历史,曝光明细 (1表示点击；0表示非点击)
0,1,U13740,11/11/2019 9:05:58 AM,N55189 N42782 N34694 N45794 N18445 N63302 N104...,N55689-1 N35729-0
1,2,U91836,11/12/2019 6:11:30 PM,N31739 N6072 N63045 N23979 N35656 N43353 N8129...,N20678-0 N39317-0 N58114-0 N20495-0 N42977-0 N...
2,3,U73700,11/14/2019 7:01:48 AM,N10732 N25792 N7563 N21087 N41087 N5445 N60384...,N50014-0 N23877-0 N35389-0 N49712-0 N16844-0 N...
3,4,U34670,11/11/2019 5:28:05 AM,N45729 N2203 N871 N53880 N41375 N43142 N33013 ...,N35729-0 N33632-0 N49685-1 N27581-0
4,5,U8125,11/12/2019 4:11:21 PM,N10078 N56514 N14904 N33740,N39985-0 N36050-0 N16096-0 N8400-1 N22407-0 N6...
5,6,U19739,11/11/2019 6:52:13 PM,N39074 N14343 N32607 N32320 N22007 N442 N19001...,N21119-1 N53696-0 N33619-1 N25722-0 N2869-0
6,7,U8355,11/11/2019 12:22:09 PM,N8419 N15771 N1431 N5888 N18663 N24123 N22130 ...,N51346-0 N33848-0 N15132-0 N10688-0 N6342-0 N6...
7,8,U46596,11/12/2019 10:29:36 PM,N47438 N20950 N21317 N5469,N7821-0 N24898-0 N12029-0 N13579-0 N42977-0 N3...
8,9,U79199,11/13/2019 10:13:02 AM,N37083 N459 N29499 N38118 N37378 N24691 N27235...,N51048-1 N64094-0 N13907-0 N39010-0
9,10,U53231,11/11/2019 11:28:11 AM,N58936 N15919 N11917 N2153 N55312 N13008 N4142...,N53585-1 N55689-0
10,11,U89744,11/14/2019 8:38:04 AM,N24422 N25287 N39121 N41777 N58226 N119 N29197...,N47572-0 N45523-0 N64560-0 N53245-0 N8509-0 N5...
11,12,U10045,11/13/2019 9:22:33 AM,N52865 N22570 N37481 N55189 N16158 N63276 N150...,N59673-0 N34876-0 N14592-0 N53470-0 N39010-0 N...
12,13,U92486,11/11/2019 5:52:04 AM,N45388 N14238 N28467 N24724 N56446 N770 N20933...,N25138-0 N61214-0 N62570-0 N36712-0 N15830-0 N...
13,14,U29155,11/14/2019 12:26:47 PM,N60785 N11885 N38939 N25114 N44984 N4830 N2068...,N44698-0 N37204-0 N36612-0 N64174-0 N29212-0 N...
14,15,U63162,11/12/2019 5:08:36 PM,N59774 N56853 N63248 N22479 N10340 N59469 N365...,N42977-0 N29468-0 N14726-0 N18887-0 N45704-0 N...
15,16,U17841,11/11/2019 10:53:09 AM,N41089 N3577 N59496 N18086 N56175 N56630 N1389...,N39587-0 N19542-1 N53214-0 N33848-0 N31763-0 N...
16,17,U8312,11/10/2019 8:18:43 AM,N22545 N44559 N32893 N33571 N4614 N56446 N5644...,N1604-0 N1034-0 N64916-0 N61145-0 N14520-0 N56...
17,18,U11306,11/11/2019 4:29:18 AM,N18064 N38868 N60340 N31801 N39778 N54842 N110...,N20811-0 N44399-0 N38783-0 N50005-0 N36703-0 N...
18,19,U38627,11/13/2019 11:18:10 AM,N21136 N306 N26026 N2309 N36530,N4642-0 N26025-0 N4913-0 N287-1 N39010-0 N5104...
19,20,U47654,11/13/2019 10:24:24 AM,N56461 N4304 N39041 N871 N44559 N28296 N41944 ...,N21420-0 N61623-0 N32519-0 N61760-0 N23162-0 N...
20,21,U70879,11/14/2019 10:45:51 AM,N47823 N44013 N17354 N26531 N22570 N16215 N298...,N38442-0 N50601-0 N36016-0 N42457-0 N23446-0 N...
21,22,U80798,11/9/2019 2:23:59 PM,N17952 N25740 N8794 N61864 N19736 N55846 N4401...,N41881-0 N27845-0 N60374-0 N47020-1 N59852-0 N...
22,23,U19722,11/13/2019 5:53:14 PM,N2028 N40613 N459 N27851 N59345 N55231 N12889 ...,N11769-0 N29517-0 N7121-0 N56548-0 N4642-0 N45...
23,24,U9306,11/12/2019 7:37:03 PM,N4099 N17953 N29177 N53636 N43295 N58936 N7714...,N20678-0 N61623-0 N18312-0 N22457-0 N50415-0 N...
24,25,U67119,11/12/2019 8:22:23 AM,N1322 N12194 N16715 N54834 N732 N14742 N17887 ...,N60105-0 N57319-0 N36789-0 N11793-0 N34998-0 N...
25,26,U91678,11/11/2019 8:20:38 AM,N15415 N3680 N19638 N9155 N848 N16636 N1603 N1...,N35729-0 N42961-0 N55689-1 N13801-0 N27581-0 N...
26,27,U12328,11/13/2019 8:43:01 AM,N1150 N13008 N12833 N1570 N48914 N15254 N27448...,N287-1 N47061-0
27,28,U44808,11/13/2019 1:14:00 PM,N61864 N22570 N56253 N871 N51706 N61864 N36053...,N51048-1 N14029-0 N4642-0 N56214-0 N8509-0
28,29,U33207,11/11/2019 11:09:14 AM,,N62212-0 N27521-0 N28983-0 N12028-0 N25437-0 N...
29,30,U36009,11/12/2019 9:13:54 PM,N33247 N58641 N64408 N30450 N11101 N11386 N214...,N59385-0 N23326-0 N50415-0 N60456-0 N17059-0 N...
30,31,U85394,11/10/2019 12:11:00 PM,N46911 N1150 N8129 N53387 N38118 N49995 N55189...,N61022-0 N49279-1 N44651-0
31,32,U6744,11/12/2019 12:21:35 PM,N9824 N58518 N57726,N17069-0 N3344-1 N64851-0 N31029-0 N63970-0 N4...
32,33,U81585,11/9/2019 1:07:20 PM,N17102 N61388 N16715 N32035 N36888 N23196 N539...,N25811-0 N3930-0 N51398-0 N7128-0 N13565-0 N43...

# 数据预处理

In [9]:
# 第一步：读取 news 获取 news ID 和 标题做映射 
new_ids = news["ID"].values.tolist()
news_titles = news["标题"].values.tolist()
news_dict = dict(zip(new_ids, news_titles))

In [10]:
# 总样本
samples = []
# 指令
instruction = "You are a news recommendation expert. Given the news click history (if the user has no news click history, indicate it as no click history) of the user and the news they like and dislike to watch, please decide whether the user likes to watch the target news by outputting \"Yes.\" or \"No.\""

In [11]:
# 第二步：读取 behaviors，获取用户喜欢和不喜欢的新闻
for idx, row in behaviors.iterrows():
    try: 
        sample_input = ""
        # print(f'曝光ID: {row["曝光ID"]}, 用户ID: {row["用户ID"]}')
        # 点击历史
        click_news_histories = []
        if len(row["曝光前的新闻点击历史"]) > 0:
            click_news = row["曝光前的新闻点击历史"].split(" ")
            
            # 如果大于3个，则直接选最后点击的3个
            if len(click_news) >= 3:
                click_news = click_news[-3:]
                
            for each_news in click_news:
                click_news_histories.append("\"" + news_dict[each_news] + "\"")
        else:
            click_news_histories.append('the user do not has click history.')
        # 曝光
        impressions = row["曝光明细 (1表示点击；0表示非点击)"].split(" ")
        likes = []
        dislikes = []
        # 前面的新闻做为训练数据，最后一个新闻做为预测
        for impression in impressions[:-1]:
            news_id, click = impression.split("-")
            news_title = news_dict[news_id]
            if int(click) == 1:
                likes.append("\""+news_title+"\"")
            else:
                dislikes.append("\""+news_title+"\"")

        sample_input = "User click histories: " + ", ".join(click_news_histories) + "\n"
        sample_input += "User likes: " + ', '.join(likes) + "\n" + "User dislikes: " + ', '.join(dislikes)

        news_id, click = impressions[-1].split("-")
        output = "Yes." if int(click) == 1 else "No."
        sample_input = sample_input + "\n" + "Whether the user will like the target news " + "\"" + news_dict[news_id] + "\"?"
        sample = {
            "instruction": instruction,
            "input": sample_input,
            "output": output,
            "用户ID": row["用户ID"]
        }
        samples.append(sample)
    except Exception as e:
        print(f'Parse {row["曝光ID"]} has exception: {e}')

In [12]:
# 查看一下样本
samples[25:30]

[{'instruction': 'You are a news recommendation expert. Given the news click history (if the user has no news click history, indicate it as no click history) of the user and the news they like and dislike to watch, please decide whether the user likes to watch the target news by outputting "Yes." or "No."',
  'input': 'User click histories: "Biggest private coal miner goes bust as Trump rescue fails", "McDonald\'s apologizes for \'Sundae Bloody Sundae\' Halloween promotion", "New York lawmakers are considering a ban on tackle football for kids under 12"\nUser likes: "Charles Rogers, former Michigan State football, Detroit Lions star, dead at 38"\nUser dislikes: "Porsche launches into second story of New Jersey building, killing 2", "Russell Wilson vs. 49ers\' No. 1 defense: Monday night\'s prime-time matchup", "60+ Restaurants Where Veterans Eat for Free on Veterans Day This Year", "Amazon\'s $1.5 million political gambit backfires in Seattle City Council election", "Andrew Yang\'s Campaign Has a Lot of Money. Now What?"\nWhether the user will like the target news "Tamron Hall Talks Leaving the Today Show, Jokes About Megyn Kelly\'s Reported Multimillion Payout"?',
  'output': 'No.',
  '用户ID': 'U91678'},
 {'instruction': 'You are a news recommendation expert. Given the news click history (if the user has no news click history, indicate it as no click history) of the user and the news they like and dislike to watch, please decide whether the user likes to watch the target news by outputting "Yes." or "No."',
  'input': 'User click histories: "Woman in \'Carrie\' costume totals car, terrifies first responders", "Heidi Klum\'s 2019 Halloween Costume Transformation Is Mind-Blowing   But, Like, What Is It?", "A New Zealand man accidentally bought 1,000 chickens online for $0.96"\nUser likes: "Three school workers charged in death of special needs student"\nUser dislikes: \nWhether the user will like the target news "105 Black Friday Deals You Can Start Shopping Today"?',
  'output': 'No.',
  '用户ID': 'U12328'},
 {'instruction': 'You are a news recommendation expert. Given the news click history (if the user has no news click history, indicate it as no click history) of the user and the news they like and dislike to watch, please decide whether the user likes to watch the target news by outputting "Yes." or "No."',
  'input': 'User click histories: "Why ex-NFL star Kellen Winslow II finally pleaded guilty to sex crimes", "Meghan McCain confronts Trump Jr.: \'You and your family have hurt a lot of people\'", "These Are The World\'s Most Magical Christmas Villages to Visit This Year"\nUser likes: "Rep. Tim Ryan endorses Biden in Democratic primary"\nUser dislikes: "A master suite with an \'open-concept\' bathroom that has no doors   or privacy   is asking for $1,200/month in rent", "Kodak Black Sentenced to Over 3 Years in Prison in Weapons Case", "Deadly Arctic blast breaks records set more than 100 years ago"\nWhether the user will like the target news "A teen received a response to a message in a bottle he wrote 9 years ago after it traveled over 3,000 miles"?',
  'output': 'No.',
  '用户ID': 'U44808'},
 {'instruction': 'You are a news recommendation expert. Given the news click history (if the user has no news click history, indicate it as no click history) of the user and the news they like and dislike to watch, please decide whether the user likes to watch the target news by outputting "Yes." or "No."',
  'input': 'User click histories: the user do not has click history.\nUser likes: "Dad bans lollipops after 5-year-old son nearly choked to death", "PEOPLE\'s Sexiest Men Alive: Still Sexy After All These Years", "See what your favorite stars look like without makeup", "Marlboro Man Bob Norris dies at 90, having reportedly never been a smoker", "Tristan Thompson Gushes Over Ex Khloe Kardashian After Her People\'s Choice Win", "Alicia Keys Goes on \'Major Rant\' Over Son\'s Fears of Being Judged for His Rainbow Manicure", "Rip Taylor\'s Cause of Death Revealed, Memorial Service Scheduled for Later This Month"\nUser dislikes: "The world\'s first hybrid cruise ship is currently on its maiden voyage\u2060 take a look inside", "Bolivian Leader Evo Morales Steps Down", "ICYMI: The week in TV news for Nov. 3-9", "Frackers Prepare to Pull Back, Exacerbating a Slowdown in U.S. Oil Growth", "Is it really easier for men to lose weight? Experts explain", "Celebrity plastic surgery transformations", "The Sexiest Photos Ever of Our 29 Sexiest Men Alive", "The Day in Sports: Sunday, November 10, 2019", "Halle Berry Shares Photo of 6-Pack Abs on Instagram and Her Fans are Freaking Out", "Iran launches nuclear enrichment at underground Fordow plant, IAEA confirms", "What\'s coming in impeachment: The inquiry goes public", "Supreme Court weighs fate of DACA, 700,000 young immigrants", "Celebrity Christmas albums: From beloved classics to big surprises", "Tamron Hall Talks Leaving the Today Show, Jokes About Megyn Kelly\'s Reported Multimillion Payout", "Cassius Winston posts heartfelt message to late brother on Instagram", "Every touchdown from every Week 10 game", "Stars who\'ve had more than one wedding with the same spouse", "Nurse takes in man with autism so he can get a new heart", "Why you should give up alcohol for one month: From improved sleep to a glowing complexion - this is EXACTLY what happens to your body when you ditch booze for just four weeks", "Top takeaways from Sunday\'s Week 10 NFL action", "What Happens When a Plane Collides with a Flock of Birds?", "Joe Giudice Calls His Family \'Italian Strong\' During Reunion with Wife Teresa and Their Daughters", "The Most Addictive Casseroles You\'re Not Making Yet", "Ahead of this week\'s rematch, Tom Brady says he\'s still not quite over Super Bowl loss to Eagles", "Big celebrity money moments of the last decade", "Comics - \'9 to 5\' by Harley Schwadron", "How Did Armistice Day Become Veterans Day in the United States?", "Neil Young Says U.S. Citizenship Application Delayed By Marijuana Use", "Stars Who Served in the Military", "The Best Beauty Looks From the 2019 People\'s Choice Awards", "Andrew Yang\'s Campaign Has a Lot of Money. Now What?", "Rare Mustang! 1968 Shelby GT500 Prototype", "Ala. lawmen help get hitchhiking disabled veteran to doctor\'s appointment across state", "The Best Beaches in Hawaii to Visit in Your Lifetime", "This is the dirtiest spot on a plane", "Australian state declares emergency due to wildfires", "People\'s Choice Awards 2019: Red Carpet Fashion", "Jamie Dimon: The \'60 Minutes\' interview", "All the Shows Hoping to Be the Next Game of Thrones", "8 television shows that didn\'t age well", "California cops respond to 2 homeless men shot with arrows: report", "Dodge Put the Wrong Wheels on 173 New Challengers and Chargers", "32 things we learned from Week 10 of NFL season", "Rebirth, angst and the \'new normal\' of California wildfires", "Are Meg Ryan and John Mellencamp Back On? Actress Seen with Engagement Ring After Breakup", "The most famous game show hosts", "Best country music albums of all time", "Pete Buttigieg clarifies views on the Obama administration after criticism for a viral misquote", "The Disney+ \'Lady and the Tramp\' remake: A guide to the new cast members", "Mixed-race mother reveals strangers question whether she\'s related to her fair-skinned daughter - including a suspicious church-goer who asked the girl: \'Is this your Mummy?\'", "Donald Trump Jr slams The View Host Sunny Hostin by asking what it\'s like to be paid by a network that \'protected pedophile - rapist Jeffrey Epstein\' in war of words on Twitter", "RHOP\'s Monique Samuels Charged With Assault After Incident With Candiace Dillard", "Kim Kardashian Looked Minty Fresh in Versace at the People\'s Choice Awards", "Man runs race in full SWAT gear, saves a life, then proposes -- all in a matter of moments", "The highlights and lowlights from the world of comedy in the 2010s", "Celebrity PDA of 2019", "\'Grandma Joy,\' grandson share photos of US as they try visiting all national parks", "Meghan Markle Smudged Makeup on a Fan\'s Coat & He Reacted Perfectly", "Here Are the Biggest Deals We\'re Anticipating for Black Friday", "I Was Adopted Here\'s What Everyone Gets Wrong About Adoption", "US Forest Service shuts down vandalized Georgia park feature", "35 musicians you should see live at least once in your life", "Mark Cuban is the latest billionaire to complain about Sen. Elizabeth Warren\'s wealth tax plan", "Hong Kong police shoot at pro-democracy protesters", "PEOPLE\'s Super Exclusive (and Very Official) Sexiest Man Alive Dads\' Club", "The Best Thanksgiving Brunch Recipes to Start Turkey Day off on a Delicious Note", "Meghan Markle Chose a Black Brocade Dress For the Royal Family\'s Important Outing", "130,000 Books Donated to Fort Worth ISD Elementary Schools", "These Are The Best Harley-Davidson Motorcycles You Can Get For The Cheap", "Cook leads Vikings to 28-24 prime-time road win over Cowboys", "Republicans have spent millions at Trump resorts since his election: report", "12 Military-Themed TV Shows to Binge-Watch on Veterans Day", "Aston Martin DBX Luxury SUV: Price, First Interior Image Released", "SEMA 2019: Cars and Trucks Gone Wild", "How the Trump Administration Eroded Its Own Legal Case on DACA", "Tennessee judge holds lawyer\'s baby as he swears her into the state bar in viral video", "Bucket-List Food Experiences in Every State", "How to spend your retirement savings without triggering a tax penalty", "From Idris Elba to Richard Gere: All the Sexiest Man Alive Covers", "5 Things No One Tells You About Living With Lung Cancer", "Megyn Kelly Charts Return to Spotlight With Social-Media Venture", "Deer-like animal thought lost to science photographed for first time in 30 years", "32 Crucial Tips for Traveling to Foreign Countries", "Jerry Jones hopes loss to Vikings isn\'t \'terminal\'", "Why Do Cats Meow?", "Nigel Farage offers Boris Johnson a truce, boosting prospects for Conservatives in December election", "For three decades, one man, now 75, has cared for Philly\'s Vietnam and Korean War memorials", "7 Women Share What It\'s Really Like To Work On A Cruise Ship", "Best, worst QB performances from NFL Week 10", "The Best Trader Joe\'s Desserts for Your Thanksgiving Dinner Table", "Amazing houses for sale in surprising places", "10 Things You Should Never Do in an Airplane Bathroom", "How to Cure Jet Lag, According to an Airline CEO", "Here\'s how social media tricks you into overspending", "Jon Hamm and Kiernan Shipka\'s Reunion Will Miss Mad Men Even More", "This Is The Moment A Senior Shelter Dog Knew He Was Safe", "Stella McCartney removes Instagram post plugging her $1,900 coat that Meghan Markle wore amid backlash", "Packers\' Preston Smith buying Rolexes for defensive teammates after reaching milestone in bet", "USA TODAY interview: Nikki Haley isn\'t running for president. That is, not yet.", "2020 Ford Bronco: Everything we know about Ford\'s new SUV", "Myanmar accused at UN court of genocide against Rohingya", "Creamed Kale Casserole, The Better Version Of Your Green Bean Fave", "LeBron James says need for load management starts at AAU level: \'AAU coaches couldn\'t give a damn about a kid\'", "Katie Couric Says Matt Lauer \'Ultimately Turned Out to Be Two Very Different People\'", "Syria\'s Assad Dismisses War Crimes Allegations in Rare Interview, Claims He Is \'Capturing the Hearts of the People\'", "What\'s in a Brand? A Look at Polestar\'s Tesla-Fighting Future", "Comparing the Trump impeachment probe to Nixon\'s", "All the ways that browsing incognito will improve your travels", "Did Meghan Markle make a change to her hair?", "30 Speedy and Delicious Potato Recipes to Make Tonight", "Poland asks Netflix to make changes to documentary about Nazi death camp guard", "Lance Altimeter Is A Delicious Drop-In Truck Camper Debuting At SEMA", "These 30 Incredible Kids Really Changed the World", "Meghan Markle Says That Archie Has Two Teeth and Is Crawling", "40 Foods Men Over 40 Should Avoid Like the Plague", "Veterans Day turns jubilant for 70-year-old Army vet after he wins lottery in NC", "The Most Amazing Photos of a Young Dolly Parton", "What to Cook This Week (November 11 to November 17)", "10 biggest disappointments of NFL Week 10", "NFL reviewing Detroit Lions\' handling of Matthew Stafford injury report", "What Joe Biden Actually Did in Ukraine", "Donald Trump Jr. reflects on explosive \'View\' chat: \'I don\'t think they like me much anymore\'", "2020 Jeep Gladiator Review: This Jeep Stands Out. Is That a Good Thing?", "I\'m Child-Free and Couldn\'t Be Happier About It. What\'s So Bad About That?", "Klobuchar: Woman with Buttigieg\'s record would miss debate", "The Tiny Hair Detail We Almost Missed in Storm Reid\'s People\'s Choice Awards Look", "The Best Backstage Moments From the 2019 E! People\'s Choice Awards", "Porsche launches into second story of New Jersey building, killing 2", "\'Sesame Street\' turns 50: Our favorite celebrity visitors to the neighborhood", "Climate change could end mortgages as we know them", "2020 GMC Sierra 3500HD Review: The Good, the Bad, and the Ugly", "A teenager thought his leukemia was a death sentence. A college football player saved his life.", "Mulvaney\'s move to join impeachment testimony lawsuit rankles Bolton allies", "Celebrity Engagements of 2019", "For a healthy heart, eat the biggest meal early in the day", "I Have Smiling Depression This Is What It Feels Like", "Gwen Stefani\'s Gown Says "Fashion Icon," So Like, No Doubt That\'s What She Is", "Deer stranded 5 miles offshore saved by Maine lobstermen", "Wild turkeys are terrorizing a town; MLB player calls on the New Jersey governor for help", "See All the Best Photos of the Royal Family at Remembrance Sunday", "The Apple Crisp That Made Me Fall in Love With...Beets", "The NFL Hot Seat: Sean McVay ran out of magic, and Jared Goff isn\'t helping", "Jess Lost 75 Pounds Without Counting Calories and Did This 1 Inspiring Thing Before Every Meal", "Russell Wilson vs. 49ers\' No. 1 defense: Monday night\'s prime-time matchup", "Charles Rogers, former Michigan State football, Detroit Lions star, dead at 38", "Flight Attendants Have a Secret Language You Didn\'t Know About", "Chin Hair: 7 Embarrassing Red Flags No Woman Should Ever Ignore", "28 Dumb Ways You Could Lose It All by Trying To Get Rich", "A former royal bodyguard shared the challenges that come with protecting the royal family", "After push from Perry, backers got huge gas deal in Ukraine", "Kentucky new No. 1 in AP Top 25 after beating Michigan State", "University suspends 14 frats after college freshman ends up in hospital", "Anthony Davis admits he is still feeling discomfort in his right shoulder", "Boeing expects 737 MAX to resume commercial service in January", "Prince Harry and Meghan Markle Will Reportedly Visit Oprah While in California", "Why Kate & Meghan Were on Different Balconies for Remembrance Sunday", "Best nostalgic pics of Leonardo DiCaprio", "Ree Drummond Says a Low-Carb Diet Is the Secret to Her Incredible Weight Loss", "Historic battlefields are finding new life as parks and refuges", "NFL Week 10 awards: Worst parachute landing goes to ...", "Bipartisan House members call on Trump to rescind Erdoğan invitation", "A body-language expert says Meghan Markle is "politely disconnecting" from the public, and honestly, we would too", "Reports: Knicks trying to hire Raptors president Masai Ujiri, could fire coach David Fizdale", "Rising temperatures put U.S. troops at risk during training, report finds", "Week in celebrity photos for Nov. 11-15, 2019", "Man who inherited 6 figures shares advice he\'d give his younger self"\nWhether the user will like the target news "Gabbard Lawyers Demand Clinton Retract \'Defamatory\' Russian Asset Comments"?',
  'output': 'No.',
  '用户ID': 'U33207'},
 {'instruction': 'You are a news recommendation expert. Given the news click history (if the user has no news click history, indicate it as no click history) of the user and the news they like and dislike to watch, please decide whether the user likes to watch the target news by outputting "Yes." or "No."',
  'input': 'User click histories: "Emotional moment lost pit bull reunites with dad", "Dad thought he dressed toddler daughter in a hat, but he was hilariously wrong", "Former Los Angeles police chief named interim in Chicago"\nUser likes: "\'It\'s the biggest gift I\'ve ever gotten:\' Iraq War veteran who lost leg and suffered significant trauma will come home to a hero\'s house in Glastonbury"\nUser dislikes: "Celebrity Engagements of 2019", "Aides are counseling Trump not to fire Mulvaney, as acting chief of staff changes course again", "\'Priceless\' finds that turned out to be worthless", "Wife of Mexico kingpin El Chapo to grace narco families TV show", "No. 1 milk company declares bankruptcy amid drop in demand", "\u200b\'My Annoying Cough Turned Out To Be Lung Cancer\'", "Hero Police Officer Saves Driver From Fiery Crash", "Protesters blockade universities, business district as chaos grips Hong Kong", "Confidence in the US economy accelerates", "2020 Ford Explorer launch hardly went according to plan, company admits", "Why This Couple Is Getting a \'Sleep Divorce\'", "Cherry disappointed with MacLean\'s apology: \'He buried me\'", "My Third Husband Is 102 Years Old. Here\'s What Our Marriage Is Like.", "\'Monday Night Football\' commentator under fire after belittling criticism of 49ers kicker for missed field goal", "Celebrity plastic surgery transformations", "The most famous celebrity kids born this decade", "Stella McCartney Deleted a Meghan Markle Instagram Post After Followers Called Her Out", "Hate crimes remain at heightened levels, FBI report finds", "Melanie Griffith Recalls Having to Pay $80,000 After Coming to Working Girl Set Intoxicated", "Unidentified remains found in woods during search for missing 5-year-old", "The Queen Had This Hilarious Reaction to (Unnecessary) Mouth-to-Mouth Resuscitation", "Barn Find: Large Collection Of Pontiac Firebirds Uncovered", "This Guy Lost 30 Pounds and Gained a Rock-Hard Six Pack", "Bode Miller delivered his twin boys after midwife didn\'t make it time for the birth", "Impeachment hearings: A look at who\'s scheduled to appear next week", "John Legend Is PEOPLE\'s Sexiest Man Alive 2019: \'I\'m Excited but a Little Scared at the Same Time\'", "Officer accused of killing Oklahoma police chief in Florida", "Copycat Cracker Barrel Chicken and Dumplings Recipe", "Trump\'s Deal Allowing 3D-Printed Guns Online Deemed Illegal", "WSU student death: Police investigating fraternity member found not breathing", "Motorcyclist walks head-first into lamppost after covering his bike"\nWhether the user will like the target news "100 Best-Ever Thanksgiving Pies"?',
  'output': 'Yes.',
  '用户ID': 'U36009'}]

In [13]:
# 第三步 划分 train 和 test 保存样本
# 首先打乱
shuffle(samples)

train = samples[:int(len(samples)*0.8)]
test = samples[int(len(samples)*0.8):]

print(f'总样本数: {len(samples)}，训练集样本数: {len(train)}，测试集样本数: {len(test)}')

with open("./data/processed/mind_train.json", "w", encoding='utf-8') as save_file:
    json.dump(train, save_file, indent=4)
    
with open("./data/processed/mind_test.json", "w", encoding='utf-8') as save_file:
    json.dump(test, save_file, indent=4) # , sort_keys=True

总样本数: 156965，训练集样本数: 125572，测试集样本数: 31393